ALTER TABLE users
ADD COLUMN IF NOT EXISTS otp VARCHAR(255),
ADD COLUMN IF NOT EXISTS otp_expires TYPE TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS otp_attempts INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS otp_block_until TIMESTAMP;