export const VIOLATION_WEIGHTS = {
  HEAD_YAW: 0.002,
  HEAD_PITCH: 0.002,
  NO_FACE: 0.005,
  MULTIPLE_FACES: 0.01,
  TAB_VISIBILITY: 5,
  WINDOW_FOCUS: 3,
  FULLSCREEN_EXIT: 8
};

export const MAX_TOTAL_SCORE = 100;
