import React from 'react'
import onlineTest from '../../../assets/illustrations/online-test.png'
import certification from '../../../assets/illustrations/certification.png'
import exam from '../../../assets/illustrations/exam.png'

const Features = () => {
    return (
        <div className='w-full '>
            <div className='w-full  bg-primary-dark rounded-lg p-5 py-14 flex gap-4'>
                <div className='w-1/3 flex gap-6  justify-center items-start'>
                    <div className='p-4 bg-[#ffffff5b] rounded-md '>
                        <img className='w-[60px]' src={onlineTest} alt="onlineTest" />
                    </div>
                    <div className='w-full flex flex-col gap-2 '>
                        <h2 className='text-[22px] font-body text-white leading-none'>AI-Driven Mock Intevriews</h2>

                        <p className='text-xs font-body text-[#ffffff73]'>Practice real interview questions generated by AI based on your role, skills, and experience level — just like a real interviewer.</p>
                    </div>
                </div>
                <div className='w-1/3 flex gap-6     justify-center items-start'>
                    <div className='p-4 bg-[#ffffff5b] rounded-md '>
                        <img className='w-[60px]' src={exam} alt="onlineTest" />
                    </div>
                    <div className='w-full flex flex-col gap-2'>
                        <h2 className='text-[22px] font-body text-white leading-none '>Real-Time Proctoring & Evaluation</h2>

                        <p className='text-xs font-body text-[#ffffff73]'>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a BC, making it over 2000 years old.</p>
                    </div>
                </div>
                <div className='w-1/3 flex gap-6     justify-center items-start'>
                    <div className='p-4 bg-[#ffffff5b] rounded-md '>
                        <img className='w-[60px]' src={certification} alt="onlineTest" />
                    </div>
                    <div className='w-full flex flex-col gap-2'>
                        <h2 className='text-[22px] font-body text-white leading-none'>Track Progress Like a Pro</h2>

                        <p className='text-xs font-body text-[#ffffff73]'>View interview history, skill-wise scores, and improvement insights after every mock interview.</p>
                    </div>
                </div>


            </div>
        </div>
    )
}

export default Features